/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 scene.gltf 
Author: mamont nikita (https://sketchfab.com/mamontnikita62)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/airplane-1b9eed11c4804b6ea0fa7668bff1b286
Title: Airplane
*/
'use client';
import React, { useRef } from 'react';
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

interface ModelProps {
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: [number, number, number];
}

export default function Model(props: ModelProps) {
  const gltf = useLoader(GLTFLoader, '/scene.gltf');
  const groupRef = useRef(null);

  return (
    <group ref={groupRef} {...props}>
      <group rotation={[-Math.PI/20, Math.PI / 5, Math.PI]} scale={[0.006, 0.006, 0.006]}>
        <primitive object={gltf.nodes.Object_2} />
        <primitive object={gltf.nodes.Object_3} />
      </group>
    </group>
  );
}

// Предварительная загрузка модели, чтобы ускорить загрузку на клиенте
useLoader.preload(GLTFLoader, '/scene.gltf');
