import React from 'react';
import { StyledMain } from './StyleMain';

export const Main = () => {
  return (
    <StyledMain>
     <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus perferendis consequuntur adipisci ab explicabo assumenda, aspernatur qui nemo, magnam amet quidem possimus dolores nam aliquid optio atque nulla placeat voluptates, suscipit sunt excepturi! Ipsa iste a molestiae incidunt culpa provident quae possimus, assumenda quaerat quia necessitatibus ad enim deleniti harum ea! Quod ad commodi, culpa veniam explicabo modi! Et, adipisci aspernatur eveniet aut aliquid at, eius maxime veritatis vero doloremque commodi iure consectetur numquam obcaecati necessitatibus facere excepturi eos, corporis minus dolor accusamus ipsum modi suscipit! Soluta ipsa est non. Numquam alias officiis assumenda animi laboriosam, minus odio doloremque inventore architecto eum reiciendis, sit, quia suscipit iusto sapiente hic reprehenderit commodi veniam dolores nisi necessitatibus modi rerum ipsa. Esse enim saepe quae culpa sit pariatur aliquid ullam delectus ducimus assumenda eaque soluta amet vero in, totam adipisci? Saepe laborum veritatis facere eveniet quia culpa minima amet nostrum fugiat, quasi esse repellendus, accusamus omnis quod? Vel maxime nemo omnis sed iusto odit voluptatum voluptatem ut. Error ut repellat sunt mollitia, ipsum eum, a cumque provident quia odio ad ea velit veritatis id incidunt, hic quod nostrum reiciendis? Vel, laudantium vero doloremque quaerat, quae velit amet sit sapiente placeat, architecto unde eius.</div>
     <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ratione in, repudiandae eius a soluta saepe recusandae similique sed, numquam dolores aspernatur? Nesciunt necessitatibus, neque dolorem soluta alias quas dicta dignissimos veniam enim eius nihil exercitationem explicabo debitis tempora hic eaque, vel laudantium vitae est obcaecati blanditiis quod dolores illum. Fugiat cum debitis illo sequi mollitia ipsam blanditiis assumenda voluptatum exercitationem quos repellendus ex alias voluptatibus vel qui atque reprehenderit nostrum odio eos ducimus, tempora nam consequuntur deleniti necessitatibus. Totam quibusdam officia consectetur quae adipisci minus consequatur libero obcaecati. Omnis tenetur numquam porro expedita nostrum! Officiis molestiae perspiciatis ipsum, doloribus aut expedita beatae saepe distinctio! Cum aut itaque dicta adipisci voluptatum rem assumenda possimus, quae, ab, corporis harum veniam expedita facilis. Ratione, maiores accusamus praesentium ullam magnam animi aspernatur aliquid fugiat a pariatur, incidunt perferendis, minus sapiente eos earum nisi doloremque repellendus suscipit quae harum saepe! Aspernatur adipisci cum perferendis.</div>
    </StyledMain>
  );
};
